# Generated by Django 3.0.7 on 2020-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=10)),
            ],
        ),
    ]
