# Generated by Django 3.0.7 on 2020-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200915_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='parent',
            new_name='device',
        ),
    ]
